# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "283e30a82af6c51cf4ddaaf2a4ac7fdc"
name = "remix-google-review"
handle = "remix-google-review"
application_url = "https://extraordinary-constant-rt-instructor.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "newstoretailwind.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://extraordinary-constant-rt-instructor.trycloudflare.com/auth/callback",
  "https://extraordinary-constant-rt-instructor.trycloudflare.com/auth/shopify/callback",
  "https://extraordinary-constant-rt-instructor.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
